services:
  db:
    image: mariadb
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    
    

  backend:
    build: ./backend
    image: node:alpine
    container_name: backend
    working_dir: /app/backend/backend
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=rJqiE9atRMmF1ba9KPk-podZkD2n5Mw0
      - NODE_ENV=development
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=adonis
      - DB_PORT=3306
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend/backend
      - backend_node_modules:/app/backend/backend/node_modules
    tty: true
    command: /bin/sh -c "yarn && node ace migration:run && yarn dev"

  frontend:
    build: ./
    image: node:alpine
    container_name: frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    command: /bin/sh -c "yarn && yarn dev"
    depends_on:
      - backend

volumes:
  dbdata:
  node_modules:
  backend_node_modules: