services:
  db:
    image: mariadb
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

  backend:
    build: ./backend
    image: node:alpine
    container_name: backend
    working_dir: /app/backend
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=adonis
      - DB_PORT=3306
    volumes:
      - type: bind
        source: ./
        target: /app/backend
      - ./:/usr/src/app/backend
      - backend_node_modules:/usr/src/app/backend/node_modules
    tty: true
    command: npm run dev

  frontend:
    build: ./
    image: node:alpine
    container_name: frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    command: npm run dev
    depends_on:
      - backend

volumes:
  dbdata:
  node_modules:
  backend_node_modules: